# Generated by Django 5.1.6 on 2025-02-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
